- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20230131035310046700000010.cnsdq4a7pewm.us-east-1.rds.amazonaws.com" 
    login_user: "david"
    login_password: "devopspblproject"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: "terraform-20230131035310046700000010.cnsdq4a7pewm.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "david" }
    - { regexp: '^database_name_here', line: "wordpressdb" }
    - { regexp: '^password_here', line: "devopspblproject" }
