- name: Install pip 
  yum:
   name: python3-pip 
   state: present


- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20230131035310046700000010.cnsdq4a7pewm.us-east-1.rds.amazonaws.com"
    login_user: "saikat"
    login_password: "devopspblproject"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-20230131035310046700000010.cnsdq4a7pewm.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "saikat" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "devopspblproject" }


